import Head from 'next/head'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Section from '../components/Section'
import Skills from '../components/Skills'

export default function Home() {
  return (
    <>
      <Head>
        <title>Javier Medina</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white dark:bg-black">
        <Navbar />
        <Hero />
        <Section />

        <Skills />
        <Footer />
      </div>
    </>
  )
}
